/** Shared demo data for db seed and the public login showcase. */

export const SEED_LOGIN_WIDGET_TOKEN =
  process.env.SEED_LOGIN_WIDGET_TOKEN ?? "seed-login-wall-carousel";

export const SEED_INSTAGRAM_URLS = [
  "https://www.instagram.com/p/DWRVGUtElO5/",
  "https://www.instagram.com/p/DTuDV_kFL87/",
  "https://www.instagram.com/p/DSwQ1pdlHC6/",
  "https://www.instagram.com/p/DVUTISRDPrR/",
  "https://www.instagram.com/p/DMf-1jjPxkM/",
  "https://www.instagram.com/p/C9AZJcExEHr/",
  "https://www.instagram.com/p/DWzPwLDDGs5/",
  "https://www.instagram.com/p/DV3ezg6j53_/",
  "https://www.instagram.com/p/DObR9C1EYKg/",
  "https://www.instagram.com/p/DRupNovgoze/",
  "https://www.instagram.com/p/DIPfuJ9CfoE/",
  "https://www.instagram.com/p/CegS2lvj-sS/",
  "https://www.instagram.com/p/DO6LSHPjJkT/",
  "https://www.instagram.com/p/DVGHXp4jWaw/",
  "https://www.instagram.com/p/DT3GaXqjFA-/",
  "https://www.instagram.com/p/C-nDLCgsEMe/",
  "https://www.instagram.com/p/DBB674IP4Nt/",
  "https://www.instagram.com/p/DKfol4cvifn/",
  "https://www.instagram.com/p/DX1TVzajPEq/",
  "https://www.instagram.com/p/DX4XfZSiEmW/",
  "https://www.instagram.com/p/DVJKwVZjLfd/",
  "https://www.instagram.com/p/DWy3AZjj-A4/",
  "https://www.instagram.com/p/DWbjvLKjPHs/",
  "https://www.instagram.com/p/DTJUwhnEjLS/",
  "https://www.instagram.com/p/DF1lQO5pM9F/",
  "https://www.instagram.com/p/DVji-RogTsj/",
  "https://www.instagram.com/p/DFYeS7mS8Dl/",
  "https://www.instagram.com/p/DUXPpXjDeZp/",
  "https://www.instagram.com/p/DYAIebsp6x8/",
  "https://www.instagram.com/p/DIeOvVOpIym/",
  "https://www.instagram.com/p/DW14TyKjKya/",
  "https://www.instagram.com/p/DRxsobSEgP9/",
  "https://www.instagram.com/p/DU3h2qQj9XQ/",
  "https://www.instagram.com/p/DYSVHr2jCwZ/",
  "https://www.instagram.com/p/DQpJEPRkZ1Q/",
  "https://www.instagram.com/p/DIGtJvnC-pS/",
] as const;

/** Matches the “wall and carousel” widget from the dashboard preview. */
export const SEED_WALL_CAROUSEL_CONFIG = {
  limit: -1,
  order: "DESC" as const,
  columns: 12,
  rows: 8,
  gap: 0,
  interval: 7800,
  swaps: 3,
  opacity: 0.25,
  background: "#0b0b0b",
  blur: 3,
  loop: true,
  visible: 5,
  cardGap: 12,
  perspective: 900,
  rotateY: 28,
  depth: 72,
  rotateX: 8,
  scaleCenter: 1.08,
  scaleSide: 0.58,
};
